services:
    # db:
    #     image: postgres:17-alpine3.21
    #     restart: always
    #     # set shared memory limit when using docker-compose
    #     shm_size: 128mb
    #     ports: [5433:5432]
    #     environment:
    #         POSTGRES_PASSWORD: bulat
    #         POSTGRES_USER: bulat
    #         POSTGRES_DB: pomodor
    #     volumes:
    #         - .data_db:/var/lib/postgresql/

    # cache:
    #     image: redis:7.2.4-alpine
    #     restart: always
    #     ports: [6377:6379]
    rabbitmq:
        image: rabbitmq:3-management-alpine
        hostname: rabbitmq
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
        volumes:
        - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
