"""access_token delete

Revision ID: d227ec957826
Revises: 3f851513f946
Create Date: 2025-04-17 12:17:15.194896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd227ec957826'
down_revision: Union[str, None] = '3f851513f946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('access_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
